### PR TITLE
client: Fixed header image bug on theme switch and added a small loading bar

### LINKED ISSUE #21: client: Styles in events page act weirdly on load
Styles act weirdly for a split second on the events page on load.

**Steps to reproduce:** Switch over to the events page

events-issue

### PR DESCRIPTION
**Pull request by heyimalaap**
also fixed #21

### CODE REVIEW

**Comment by ghpranav** [comment]
@heyimalaap any particular reason as to why you want to pre-load the event's page CSS during initial render of the home page?

**Comment by heyimalaap** [comment]
@ghpranav for some reason, there were a few times on switching pages that the styles for event page didn't even load, so i ended up preloading it. It's small it begin with so I don't think it will effect performance too.

**Comment by ghpranav** [comment]
Alright, I'll merge the PR for now. We can measure the performance impact & defer the non-critical CSS later.

**Comment by heyimalaap** [comment]
Yep! sounds cool. I honestly don't know why the styles didn't load sometimes. So, if someone found out why that is the case, plz fix and let me know.

**Pull request merged**
